const GalleryActionTypes = {
  SET_POSTS_FETCH_PARAMS: 'SET_POSTS_FETCH_PARAMS',

  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FALIURE: 'FETCH_POSTS_FALIURE',

  FETCH_NEXT_PAGE_POSTS_START: 'FETCH_NEXT_PAGE_POSTS_START',
  FETCH_NEXT_PAGE_POSTS_SUCCESS: 'FETCH_NEXT_PAGE_POSTS_SUCCESS',
  FETCH_NEXT_PAGE_POSTS_FALIURE: 'FETCH_NEXT_PAGE_POSTS_FALIURE',
};

export default GalleryActionTypes;
