const GalleryActionTypes = {
  SET_POSTS_FETCH_PARAMS: 'SET_POSTS_FETCH_PARAMS',

  UPDATE_POST: 'UPDATE_POST',

  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FALIURE: 'FETCH_POSTS_FALIURE',

  FETCH_POSTS_BY_ID_START: 'FETCH_POSTS_BY_ID_START',
  FETCH_POSTS_BY_ID_SUCCESS: 'FETCH_POSTS_BY_ID_SUCCESS',
  FETCH_POSTS_BY_ID_NOT_FOUND: 'FETCH_POSTS_BY_ID_NOT_FOUND',
  FETCH_POSTS_BY_ID_FALIURE: 'FETCH_POSTS_BY_ID_FALIURE',

  FETCH_NEXT_PAGE_POSTS_START: 'FETCH_NEXT_PAGE_POSTS_START',
  FETCH_NEXT_PAGE_POSTS_SUCCESS: 'FETCH_NEXT_PAGE_POSTS_SUCCESS',
  FETCH_NEXT_PAGE_POSTS_FALIURE: 'FETCH_NEXT_PAGE_POSTS_FALIURE',

  DELETE_POST_START: 'DELETE_POST_START',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FALIURE: 'DELETE_POST_FALIURE',
};

export default GalleryActionTypes;
