const CategoriesActionTypes = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FALIURE: 'FETCH_CATEGORIES_FALIURE',
  SET_FETCH_PARAMS: 'SET_FETCH_PARAMS',
};

export default CategoriesActionTypes;
