const CategoriesActionTypes = {
  SET_CATEGORIES_FETCH_PARAMS: 'SET_CATEGORIES_FETCH_PARAMS',
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FALIURE: 'FETCH_CATEGORIES_FALIURE',
  ADD_CATEGORY_START: 'ADD_CATEGORY_START',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FALIURE: 'ADD_CATEGORY_FALIURE',
  DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FALIURE: 'DELETE_CATEGORY_FALIURE',
  DELETE_CATEGORIES_START: 'DELETE_CATEGORIES_START',
  DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
  DELETE_CATEGORIES_FALIURE: 'DELETE_CATEGORIES_FALIURE',
  UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FALIURE: 'UPDATE_CATEGORY_FALIURE',
};

export default CategoriesActionTypes;
