const PostDialogActionTypes = {
  FETCH_CATEGORIES_LIST_BY_QUERY_START: 'FETCH_CATEGORIES_LIST_BY_QUERY_START',
  FETCH_CATEGORIES_LIST_BY_QUERY_SUCCESS:
    'FETCH_CATEGORIES_LIST_BY_QUERY_SUCCESS',
  FETCH_CATEGORIES_LIST_BY_QUERY_FALIURE:
    'FETCH_CATEGORIES_LIST_BY_QUERY_FALIURE',

  ADD_POST_STRART: 'ADD_POST_STRART',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FALIURE: 'ADD_POST_FALIURE',
};

export default PostDialogActionTypes;
